### ISSUE TITLE
[Document: 문서] 인터페이스 설계 업데이트

### ISSUE THREAD

**Issue by dubu4050** [dubu4050/nyang_node_server#3]
## 요구 사항:  회의내용 반영하여 [[Document] Interface 설계 명세](https://github.com/dubu4050/nyang_node_server/wiki/%5BDocument%5D-Interface-%EC%84%A4%EA%B3%84-%EB%AA%85%EC%84%B8) 업데이트
※ 참고: [[Document] 비즈니스 유스케이스 및 유스케이스](https://github.com/dubu4050/nyang_node_server/wiki/%5BDocument%5D-%EB%B9%84%EC%A6%88%EB%8B%88%EC%8A%A4-%EC%9C%A0%EC%8A%A4%EC%BC%80%EC%9D%B4%EC%8A%A4-%EB%B0%8F-%EC%9C%A0%EC%8A%A4%EC%BC%80%EC%9D%B4%EC%8A%A4)
- [x] 설계 명세 및 wiki 업데이트

**Comment by Jungwoo-20** [comment]
[[nyang]_인터페이스_설계_v.0.2.pdf](https://github.com/dubu4050/nyang_node_server/files/6177486/nyang._._._v.0.2.pdf)
